requires "Kossy", 0.38;
requires "DBIx::Sunny";

requires "Cache::Memcached::Fast";
requires "DBD::Pg";
requires "Starman";
requires "Plack::Session";
requires "Furl";
requires "Gazelle";
requires "IO::Socket::SSL";
requires "String::Util";
requires "Redis::Fast";
